login: &login
  adapter: mysql2
  host: localhost
  username: okaapi
  password: 0kap1
  encoding: utf8
  
development:
  database: jsonview
  <<: *login

production:
  database: jsonview
  <<: *login

test:
  database: jsonview_test
  <<: *login